/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package irrgarten.UI;

import irrgarten.Directions;

/**
 *
 * @author juan
 */
public class Cursors extends javax.swing.JDialog {
    
    
    private Directions direction;
    
    public Directions getDirection(){
        setVisible(true);
        return direction;
    }
    /**
     * Creates new form Cursors
     */
    public Cursors(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upBoton = new javax.swing.JButton();
        leftBoton = new javax.swing.JButton();
        rightBoton = new javax.swing.JButton();
        downBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        upBoton.setText("UP");
        upBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upBotonActionPerformed(evt);
            }
        });

        leftBoton.setText("LEFT");
        leftBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftBotonActionPerformed(evt);
            }
        });

        rightBoton.setText("RIGHT");
        rightBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightBotonActionPerformed(evt);
            }
        });

        downBoton.setText("DOWN");
        downBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(leftBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(rightBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(downBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(upBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(upBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftBoton)
                    .addComponent(rightBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(downBoton)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void upBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upBotonActionPerformed
        direction=Directions.UP;
        dispose();
    }//GEN-LAST:event_upBotonActionPerformed

    private void leftBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftBotonActionPerformed
        direction=Directions.LEFT;
        dispose();
    }//GEN-LAST:event_leftBotonActionPerformed

    private void downBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downBotonActionPerformed
        direction=Directions.DOWN;
        dispose();
    }//GEN-LAST:event_downBotonActionPerformed

    private void rightBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightBotonActionPerformed
        direction=Directions.RIGHT;
        dispose();
    }//GEN-LAST:event_rightBotonActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton downBoton;
    private javax.swing.JButton leftBoton;
    private javax.swing.JButton rightBoton;
    private javax.swing.JButton upBoton;
    // End of variables declaration//GEN-END:variables
}
